version: "3"

services:
  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    env_file: ./backend/.env # injected into container from specified .env file
    environment: # injected from root .env file
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - strapi-app-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "1337:1337"
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    networks:
      - strapi-app-network
    volumes:
      - strapidata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - strapi-app-network
    ports:
      - 3000:3000
    environment:
      HOST: 0.0.0.0
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 3000
      BACKEND_URL: http://host.docker.internal:1337
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.nuxt
    restart: unless-stopped

networks:
  strapi-app-network:
    driver: bridge

volumes:
  strapidata: